In [4]:
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler , LabelEncoder
import joblib
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score,f1_score

In [5]:
import pandas as pd
data=pd.read_csv("/content/movies_music_recommendation_100.csv")
data=data.drop(columns=["genre"])
df=pd.DataFrame(data)
df

,id,title,type,mood,language,rating,popularity
0,1,Inception,Movie,Exciting,English,8.8,95
1,2,Titanic,Movie,Sad,English,7.9,90
2,3,3 Idiots,Movie,Happy,Hindi,8.4,92
3,4,The Dark Knight,Movie,Serious,English,9.0,98
4,5,Dangal,Movie,Inspiring,Hindi,8.3,88
...,...,...,...,...,...,...,...
95,96,Raabta,Music,Emotional,Hindi,4.7,88
96,97,Counting Stars Acoustic,Music,Emotional,English,4.5,84
97,98,Tum Ho,Music,Sad,Hindi,4.9,91
98,99,Bones,Music,Exciting,English,4.6,86
99,100,Tera Hone Laga Hoon,Music,Happy,Hindi,4.8,89

In [6]:
df.shape

(100, 7)

In [7]:
df.size

700

In [8]:
df.columns

Index(['id', 'title', 'type', 'mood', 'language', 'rating', 'popularity'], dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          100 non-null    int64
 1   title       100 non-null    object
 2   type        100 non-null    object
 3   mood        100 non-null    object
 4   language    100 non-null    object
 5   rating      100 non-null    float64
 6   popularity  100 non-null    int64
dtypes: float64(1), int64(2), object(4)
memory usage: 5.6+ KB

In [10]:
df.describe()

               id      rating  popularity
count  100.000000  100.000000  100.000000
mean    50.500000    6.406000   88.590000
std     29.011492    1.733265    4.087663
min      1.000000    4.400000   78.000000
25%     25.750000    4.700000   86.000000
50%     50.500000    6.950000   88.500000
75%     75.250000    8.100000   91.000000
max    100.000000    9.300000   99.000000

In [11]:
df.isnull()

       id  title   type   mood  language  rating  popularity
0   False  False  False  False     False   False       False
1   False  False  False  False     False   False       False
2   False  False  False  False     False   False       False
3   False  False  False  False     False   False       False
4   False  False  False  False     False   False       False
..    ...    ...    ...    ...       ...     ...         ...
95  False  False  False  False     False   False       False
96  False  False  False  False     False   False       False
97  False  False  False  False     False   False       False
98  False  False  False  False     False   False       False
99  False  False  False  False     False   False       False

[100 rows x 7 columns]

In [12]:
df.isnull().sum().sum()

np.int64(0)

In [13]:
models={
    "SVC1":SVC(kernel='linear'),
    "SVC2":SVC(kernel="rbf"),
    "LOGISTIC":LogisticRegression(),
    "DC":DecisionTreeClassifier(random_state=5050),
    "RF":RandomForestClassifier(n_estimators=200,random_state=2020),
    "knc":KNeighborsClassifier(n_neighbors=5),
    "NB":GaussianNB()
}
result={}

In [14]:
x=df.iloc[ : , :-1]

In [15]:
y=df.iloc[ : ,-1]

In [16]:
x

     id                    title   type       mood language  rating
0     1                Inception  Movie   Exciting  English     8.8
1     2                  Titanic  Movie        Sad  English     7.9
2     3                 3 Idiots  Movie      Happy    Hindi     8.4
3     4          The Dark Knight  Movie    Serious  English     9.0
4     5                   Dangal  Movie  Inspiring    Hindi     8.3
..  ...                      ...    ...        ...      ...     ...
95   96                   Raabta  Music  Emotional    Hindi     4.7
96   97  Counting Stars Acoustic  Music  Emotional  English     4.5
97   98                   Tum Ho  Music        Sad    Hindi     4.9
98   99                    Bones  Music   Exciting  English     4.6
99  100      Tera Hone Laga Hoon  Music      Happy    Hindi     4.8

[100 rows x 6 columns]

In [17]:
y

0     95
1     90
2     92
3     98
4     88
      ..
95    88
96    84
97    91
98    86
99    89
Name: popularity, Length: 100, dtype: int64

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=51,test_size=0.2)

In [19]:
x_train.shape

(80, 6)

In [20]:
x_test.shape

(20, 6)

In [21]:
y_train.shape

(80,)

In [22]:
y_test.shape

(20,)

In [23]:
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler , LabelEncoder
import joblib
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score,f1_score


categorical_cols = x_train.select_dtypes(include='object').columns


x_train_encoded = x_train.copy()
x_test_encoded = x_test.copy()

for col in categorical_cols:
    le = LabelEncoder()

    all_unique_values = pd.concat([x_train_encoded[col], x_test_encoded[col]]).unique()
    le.fit(all_unique_values)

    x_train_encoded[col] = le.transform(x_train_encoded[col])
    x_test_encoded[col] = le.transform(x_test_encoded[col])

for name,model in models.items():

  pipe=Pipeline([
      ("scale",MinMaxScaler()),
      ("model",model)
  ])


  pipe.fit(x_train_encoded,y_train)
  y_pred=pipe.predict(x_test_encoded)

  acc=accuracy_score(y_test,y_pred)

  pre=precision_score(y_test,y_pred, average='weighted', zero_division=0)
  f1=f1_score(y_test,y_pred, average='weighted', zero_division=0)
  rec=recall_score(y_test,y_pred, average='weighted', zero_division=0)
  cm=confusion_matrix(y_test,y_pred)

  result[name]={
      "model":pipe,
      "acc":acc,
      "pre":pre,
      "f1":f1,
      "rec":rec,
      "cm":cm
  }
  print("\n",name)
  print("acc",acc),
  print("pre",pre),
  print("rc",rec),
  print("f1",f1),
  print("cm",cm)

 SVC1
acc 0.15
pre 0.05
rc 0.15
f1 0.075
cm [[0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 3 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 1 0 0 0 0 0]
 [0 0 0 0 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]]

 SVC2
acc 0.05
pre 0.02857142857142857
rc 0.05
f1 0.03636363636363636
cm [[0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 1 0 0 0 0 0]
 [0 0 0 0 0 2 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0]]

 LOGISTIC
acc 0.1
pre 0.04444444444444444
rc 0.1
f1 0.06153846153846154
cm [[0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 2 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 1 0 0 0 0 0]
 [0 0 0 0 0 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0]]

 DC
acc 0.15
pre 0.225
rc 0.15
f1 0.17666666666666667
cm [[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 2 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]]

 RF
acc 0.15
pre 0.16
rc 0.15
f1 0.13333333333333333
cm [[0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 2 1 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1]]

 knc
acc 0.0
pre 0.0
rc 0.0
f1 0.0
cm [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 1 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 1 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]]

 NB
acc 0.05
pre 0.04
rc 0.05
f1 0.04444444444444444
cm [[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 1 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0 0 0 1 0 0]
 [0 0 1 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]]

In [24]:
best_model=max(result,key=lambda x:result[x]["acc"])
best_pipe=result[best_model]["model"]

In [25]:
best_model

'SVC1'

In [26]:
best_pipe

Pipeline(steps=[('scale', MinMaxScaler()), ('model', SVC(kernel='linear'))])

In [27]:
joblib.dump(best_pipe,'best_pipeline.joblib')

['best_pipeline.joblib']